//
// Created by cuadriante on 7/10/21.
//

#ifndef DATOSII_PROYECTOII_IMAGE_RECOVERY_IMAGELOADER_H
#define DATOSII_PROYECTOII_IMAGE_RECOVERY_IMAGELOADER_H


class ImageLoader {

};


#endif //DATOSII_PROYECTOII_IMAGE_RECOVERY_IMAGELOADER_H
